# Generated by Django 5.2.5 on 2025-08-29 00:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('min_price_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_settings', to='shop.shop')),
            ],
        ),
    ]
