# Generated by Django 5.2.5 on 2025-09-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_client_shopsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='allow_direct_orders',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='custom_domain',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='show_contact_info',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Rendre la boutique visible au public'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='shareable_link_slug',
            field=models.SlugField(blank=True, help_text="Nom personnalisé pour le lien de la boutique (ex: 'boutique-de-jane'). Laissez vide pour utiliser le nom d'utilisateur.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
