# Generated by Django 5.2.6 on 2025-10-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_shopsettings_allow_direct_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variation_images/'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'type', 'value')},
        ),
        migrations.CreateModel(
            name='CartItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cartitem')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariation')),
            ],
            options={
                'unique_together': {('cart_item', 'variation')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_variations',
            field=models.ManyToManyField(blank=True, through='shop.CartItemVariation', to='shop.productvariation'),
        ),
        migrations.CreateModel(
            name='OrderItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariation')),
            ],
            options={
                'unique_together': {('order_item', 'variation')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_variations',
            field=models.ManyToManyField(blank=True, through='shop.OrderItemVariation', to='shop.productvariation'),
        ),
        migrations.CreateModel(
            name='VariationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_groups', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariation')),
                ('variation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.variationgroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('variation_group', 'variation')},
            },
        ),
    ]
