# Generated by Django 5.2.6 on 2025-10-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderitem_variations_data_productvariation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active_in_chat', models.BooleanField(default=False)),
                ('current_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='shop.merchant')),
            ],
            options={
                'verbose_name': 'Activité du commerçant',
                'verbose_name_plural': 'Activités des commerçants',
            },
        ),
    ]
